### ISSUE TITLE
Expose data through xAPI

### ISSUE THREAD

**Issue by christianp** [numbas/numbas-lti-provider#10]
[xAPI](http://experienceapi.com/) is the follow-up to SCORM that is trying to standardise the storing and sharing of data about "learning experiences". It would be good to expose data about activity in the Numbas LTI provider through xAPI.

Data is supposed to flow from a learning tool to a Learning Record Store. I googled for an open source LRS, and [Learning Locker](https://learninglocker.net/) came up.

Rather than writing tons of reports inside the LTI tool, using xAPI might let us use other tools to analyse attempt data.

**Comment by dcollien** [comment]
[WatershedLRS](https://www.watershedlrs.com/) can also be used (they have a free tier LRS which is useful for testing without additional setup).

I haven't seen a standard way of passing xAPI credentials to an LTI Provider, but I imagine it would be fairly easy to do as per the format here: http://www.xapilaunchlink.com/ but instead of URL parameters, using LTI custom or ext parameters, e.g. the Provider may wish to receive:

* custom_lrs_endpoint
* custom_lrs_auth
* custom_lrs_actor
* custom_lrs_registration

or perhaps  an xAPI LRS launch profile which includes:
* ext_lrs_endpoint
* ext_lrs_auth
* ext_lrs_actor
* ext_lrs_registration

I would be interested if there's any consensus on how to do this

**Comment by jhoobergs** [comment]
cmi5 seems to be the way to convert SCORM data to xAPI data: https://aicc.github.io/CMI-5_Spec_Current/SCORM/
