### ISSUE TITLE
Don't hide broken attempts from the student

### ISSUE THREAD

**Issue by christianp** [numbas/numbas-lti-provider#18]
When an attempt is missing the `cmi.suspend_data` element, it's marked as "broken" and hidden from the student, then a fresh attempt is begun.
We should be more up-front about what happens: the broken attempt should be visible with some kind of warning message, and count towards the final score, but not the number of attempts taken.

We had an attempt which was marked as broken but had the `cmi.suspend_data` element many times, so I'm not sure how it ended up getting marked as broken - maybe the student refreshed the page during load?

**Comment by oscarsiles** [comment]
> We had an attempt which was marked as broken but had the cmi.suspend_data element many times, so I'm not sure how it ended up getting marked as broken - maybe the student refreshed the page during load?

We are having some issues with this in particular, where about 5-10% of student attempts are showing as "Broken" and resetting the student progress, but everything looks OK in the SCORM data except this field is repeated several times. I am trying to piece together some data as to why this is happening, but wondered if you had any insight into the issue since your original post?

**Comment by christianp** [comment]
I don't have any more to add on this, sorry. I haven't managed to reproduce this problem myself, so it's proving hard to pin down.
