### ISSUE TITLE
Unable to review a Numbas test with an unchecked 'Show results page?'

### ISSUE THREAD

**Issue by JoshuaCapel** [numbas/numbas-lti-provider#54]
The people at my institution have spun up a Numbas LTI server but we are encountering an unexpected behaviour (I don't think it's a bug, more like an odd feature).

Everything seems to be working fine so far. I can export our tests as SCORM packages from the editor and uploading them to the LTI when I am making an external activity in Moodle. And the LTI server appears to be correctly recording result.

However if the test we exported had the ['Show results page?'](https://docs.numbas.org.uk/en/latest/exam/reference.html#term-show-results-page) box unchecked, then the [review button](https://numbas-lti-provider.readthedocs.io/en/latest/instructor/resources.html#review-an-attempt) in the instructor view does not actually show the results for the instructor to review. Instead it jumps straight to "The exam has finished. You may now close this window.".

If we tick the 'Show results page?' box and reupload then reviewing works fine.

The documentation say that the "review mode always opens attempts as if they were completed, even if the student has not yet ended the exam.". So it seems that if the students cannot review their results at the end of a test, then neither can we.

**Comment by christianp** [comment]
That's the expected behaviour at the moment, but you're right it's not very helpful.

The SCORM standard doesn't really imagine anyone other than the student running an activity - the Numbas review mode is sort of an abuse of the available tools. 

We could fix this by adding an element like `x.learner_role` to the SCORM data model, and override the "show results page" setting if the role isn't "student".

I'm wary of adding too much non-SCORM stuff to the LTI provider because it would lead us down the slippery slope towards requiring the LTI provider, but maybe I shouldn't be.

**Comment by christianp** [comment]
The results page is now always shown to instructors.
